- name: Install postgres and some other dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-dev
  become: True

- name: Restart postgres
  service: name=postgresql state=restarted
  become: True

- name: Install python psycopg2 module
  pip: name=psycopg2 state=present
  become: True

- name: Create a postgres user
  postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_pass }}"
    role_attr_flags: CREATEDB
  become: True
  become_user: postgres

- name: Create the postgres database
  postgresql_db:
    name: "{{ postgres_db }}"
    owner: "{{ postgres_user }}"
  become: True
  become_user: postgres