- name: Create exploder configuration directory
  file: path={{ exploder_conf_dir }} state=directory

- name: Copy the configuration file
  template: src=templates/exploder.conf dest={{ exploder_conf_dir }}/exploder.conf

- name: Add the EXPLODER_CONFIG environment variable to .bashrc
  lineinfile:
    dest={{ ansible_env.HOME }}/.bashrc
    line="export EXPLODER_CONFIG={{ exploder_conf_dir }}/exploder.conf"
    state=present
    insertafter=EOF
    create=True

- name: Install the application (production version)
  pip: chdir={{ code_dir }} state=present name=.
  when:
    - production == True
  become: True

- name: Install the application (development version)
  command: chdir={{ code_dir }} /usr/bin/python setup.py develop
  when:
    - production == False
  become: True

- name: Copy the app supervisor conf file
  template: src=templates/exploder-supervisor.conf dest=/etc/supervisor/conf.d/exploder-supervisor.conf
  become: True

- name: Restart the supervisor app
  supervisorctl:
    name: "{{ item }}"
    state: restarted
  with_items:
    - exploder-api1
    - exploder-api2
  become: True

- name: Copy the nginx conf file
  template: src=templates/exploder-nginx.conf dest=/etc/nginx/sites-available/exploder-nginx.conf
  become: True

- name: Disable the default website
  file: path=/etc/nginx/sites-enabled/default state=absent
  become: True

- name: Enable the application in nginx
  file: src=/etc/nginx/sites-available/exploder-nginx.conf dest=/etc/nginx/sites-enabled/exploder-nginx.conf state=link
  become: True

- name: Restart nginx
  service: name=nginx state=restarted
  become: True