- name: Install fail2ban module
  apt: name=fail2ban state=present update_cache=yes
  become: True

- name: Copy fail2ban local config file
  template: src=templates/jail.local dest=/etc/fail2ban/jail.local
  become: True

- name: Copy nginx-block-users.conf file
  template: src=templates/nginx-block-users.conf dest=/etc/fail2ban/filter.d/nginx-block-users.conf force=yes
  become: True

- name: Restart fail2ban
  service: name=fail2ban state=restarted
  become: True
